# This is a basic workflow to help you get started with Actions

name: CI
run-name: ${{ github.actor }} has been starting the workflow

env:
  GITHUB_ACTIONS: Some value

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "github-task-job"
  github-task-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "The value of environment variable is ${{ env.GITHUB_ACTIONS }}"
      - run: echo "The name of the branch is ${{ github.ref }}. The name of repository is ${{ github.repository }}"
      - run: echo "The job was triggered by event ${{ github.event_name }}"

